# Generated by Django 3.0.9 on 2020-10-27 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_image', models.ImageField(upload_to='accommodation')),
                ('accommodation_title', models.CharField(max_length=50)),
                ('accommodation_subtitle', models.CharField(max_length=50)),
                ('accommodation_option', models.CharField(max_length=50)),
                ('accommodation_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='전화번호')),
            ],
            options={
                'verbose_name_plural': '숙박시설',
            },
        ),
        migrations.CreateModel(
            name='Coveniences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coveniences_image', models.ImageField(upload_to='coveniences')),
                ('coveniences_title', models.CharField(max_length=50)),
                ('coveniences_subtitle', models.CharField(max_length=50)),
                ('coveniences_option', models.CharField(max_length=50)),
                ('coveniences_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='전화번호')),
            ],
            options={
                'verbose_name_plural': '편의시설',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('option', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='전화번호')),
            ],
            options={
                'verbose_name_plural': '맛집',
            },
        ),
        migrations.CreateModel(
            name='Surfschool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surfschool_image', models.ImageField(upload_to='surfschool')),
                ('surfschool_title', models.CharField(max_length=50)),
                ('surfschool_subtitle', models.CharField(max_length=50)),
                ('surfschool_option', models.CharField(max_length=50)),
                ('surfschool_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='전화번호')),
            ],
            options={
                'verbose_name_plural': '서핑스쿨',
            },
        ),
        migrations.AlterModelOptions(
            name='forcastdata',
            options={'ordering': ['category'], 'verbose_name_plural': 'spot스팟정보'},
        ),
        migrations.AddField(
            model_name='forcastdata',
            name='lat',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forcastdata',
            name='lng',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airTemperature', models.FloatField(blank=True, null=True)),
                ('waterTemperature', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('cloudCover', models.FloatField(blank=True, null=True)),
                ('waveDirection', models.FloatField(blank=True, null=True)),
                ('waveHeight', models.FloatField(blank=True, null=True)),
                ('wavePeriod', models.FloatField(blank=True, null=True)),
                ('windDirection', models.FloatField(blank=True, null=True)),
                ('gust', models.FloatField(blank=True, null=True)),
                ('weather_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('spot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spot', to='spot.ForcastData')),
            ],
            options={
                'verbose_name_plural': 'weather',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='forcastdata',
            name='accommodation_tag',
            field=models.ManyToManyField(blank=True, related_name='accommodation', to='spot.Accommodation'),
        ),
        migrations.AddField(
            model_name='forcastdata',
            name='coveniences_tag',
            field=models.ManyToManyField(blank=True, related_name='coveniences', to='spot.Coveniences'),
        ),
        migrations.AddField(
            model_name='forcastdata',
            name='food_tag',
            field=models.ManyToManyField(blank=True, related_name='food', to='spot.Food'),
        ),
        migrations.AddField(
            model_name='forcastdata',
            name='surfshool_tag',
            field=models.ManyToManyField(blank=True, related_name='surfschool', to='spot.Surfschool'),
        ),
    ]
