# Generated by Django 3.1.1 on 2020-10-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='school.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=200, verbose_name='설명')),
                ('address', models.CharField(max_length=50, verbose_name='주소')),
                ('phone_number', models.CharField(max_length=50, verbose_name='전화번호')),
                ('link', models.URLField(verbose_name='홈페이지')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('parking', models.BooleanField(verbose_name='주차')),
                ('reservation', models.BooleanField(verbose_name='예약')),
                ('wifi', models.BooleanField(verbose_name='와이파이')),
                ('shower', models.BooleanField(verbose_name='샤워')),
                ('amenities', models.BooleanField(verbose_name='어메니티')),
                ('lat', models.FloatField(max_length=100, verbose_name='위도')),
                ('lng', models.FloatField(max_length=100, verbose_name='경도')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='school.category')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
