# Generated by Django 3.0.9 on 2020-10-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20201012_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='홈페이지'),
        ),
    ]
