# Generated by Django 3.0.9 on 2020-11-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201119_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='이름을 입력하시오', max_length=30, verbose_name='이름'),
        ),
    ]
