# Generated by Django 3.0.9 on 2020-10-22 02:54
from django.db import migrations
from oscar.apps.payment.models import SourceType

from iamport.models import PGProviders


def create_payment_source_type(apps, schema_editor):
    for value, _ in PGProviders.choices:
        SourceType.objects.get_or_create(name=value, code=value)


class Migration(migrations.Migration):
    dependencies = [
        ('payment', '0004_auto_20181115_1953'),
    ]

    operations = [
        migrations.RunPython(create_payment_source_type)
    ]
