# Generated by Django 3.1.1 on 2020-09-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commu', '0002_auto_20200913_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
