# Generated by Django 3.1.1 on 2020-09-13 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commu', '0005_auto_20200913_0425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
