# Generated by Django 3.1.1 on 2020-09-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_key', models.CharField(max_length=500)),
                ('thumbnail', models.CharField(max_length=500)),
                ('video_desc', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
